apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-oauthproxy"
  labels:
    app: oauthproxy
spec:
  selector:
    app: oauthproxy
  ports:
    - name: http
      port: 9000
      targetPort: http
