apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-runtime"
  labels:
    app: runtime
spec:
  selector:
    app: runtime
  ports:
    - port: 9001
      name: external
      protocol: TCP
      targetPort: 9001
