apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-graphql"
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: "{{ .Values.graphql.image }}"
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: JWT_VERIFICATION_KEY
              value: {{ required "A .Values.auth.jwt.key is required" .Values.auth.jwt.key }}
            - name: DATABASE_URL
              # used to connect to db
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: public
