apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-graphql"
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: "{{ .Values.graphql.image }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: JWT_VERIFICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-auth"
                  key: jwt_secret_key
            - name: DATABASE_URL
              # used to connect to db
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: public
            - name: WHITELIST_DOMAINS_REGEXP
              value: {{ .Values.graphql.corsWhitelistRegexp }}
            - name: CREDS_URL
              value: {{ printf "http://%s-creds.%s.svc.cluster.local:9000" .Release.Name .Release.Namespace }}
