apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-http"
spec:
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: http
          image: "{{ .Values.http.image }}"
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: RUNTIME_URL
              value: {{ printf "http://%s-runtime.%s.svc.cluster.local:9001" .Release.Name .Release.Namespace }}
            - name: DOMAIN
              value: "http.{{ .Values.domain }}"
