apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-database-init"
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-database-init"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: database-init-job
          image: williammartin/schema
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: sqitch-url
