apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-sls"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sls
  template:
    metadata:
      labels:
        app: sls
    spec:
      containers:
        - name: sls
          image: {{ include "storyscript.image" .Values.sls.image }}
          ports:
          - name: http
            containerPort: 2042
          env:
            - name: STORYSCRIPT_HUB_API
              value: http{{ ternary "s" "" .Values.tls.enabled }}://api.{{ .Values.domain }}/graphql
