apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-router"
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: {{ include "storyscript.image" .Values.router.image }}
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: HTTP_INGRESS_URL
              value: {{ printf "%s-http.%s.svc.cluster.local:9000" .Release.Name .Release.Namespace }}
            - name: DEFAULT_DOMAIN
              value: "{{ .Values.appsDomain }}"
            - name: DATABASE_URL
              # used to connect to db
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-database-credentials"
                  key: superuser-search_path
            - name: TLS_CERT
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-tls-cert"
                  key: tls.crt
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-tls-cert"
                  key: tls.key
