apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-router"
  labels:
    app: router
spec:
  selector:
    app: router
  ports:
    - port: 443
      targetPort: 9000
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.router.loadBalancerIP }}"
