apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-studio"
type: Opaque
data:
  intercom_app_id: {{ required "A .Values.studio.integrations.intercom is required" .Values.studio.integrations.intercom | b64enc }}
  fs_org_id: {{ required "A .Values.studio.integrations.fullstory is required" .Values.studio.integrations.fullstory | b64enc }}
  sentry_dsn: {{ required "A .Values.studio.sentry.dsn is required" .Values.studio.sentry.dsn | b64enc }}
