apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-geh"
  labels:
    app: geh
spec:
  selector:
    app: geh
  ports:
    - port: 3000
      name: external
      protocol: TCP
      targetPort: 3000
