apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-geh"
  labels:
    app: geh
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
     - "events.{{ .Values.domain }}"
    secretName: "{{ .Release.Name }}-tls-cert"
  {{- end }}
  rules:
  - host: "events.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-geh"
          servicePort: 3000
