apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-geh"
type: Opaque
data:
  slack_signing_key: {{ required "A .Values.geh.slack_signing_key is required" .Values.geh.slack_signing_key | b64enc }}
