apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-auth"
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - port: 3000
      name: external
      protocol: TCP
      targetPort: 3000
