apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-auth"
  labels:
    app: auth
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.tls.enabled }}
  tls:
  - hosts:
     - "auth.{{ .Values.domain }}"
    secretName: "{{ .Release.Name }}-tls-cert"
  {{- end }}
  rules:
  - host: "auth.{{ .Values.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Release.Name }}-auth"
          servicePort: 3000
