apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-auth-config"
type: Opaque
data:
  jwt_secret_key: {{ required "A .Values.auth.jwt.secret_key is required" .Values.auth.jwt.secret_key | b64enc }}
  github_client_id: {{ required "A .Values.auth.github.client_id is required" .Values.auth.github.client_id | b64enc }}
  github_client_secret: {{ required "A .Values.auth.github.client_secret is required" .Values.auth.github.client_secret | b64enc }}
