apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-compiler"
  labels:
    app: compiler
spec:
  selector:
    app: compiler
  ports:
    - port: 80
      name: external
      protocol: TCP
      targetPort: 5001
