apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-creds-config"
type: Opaque
data:
  github_client_id: {{ required "A .Values.creds.github.client_id is required" .Values.creds.github.client_id | b64enc }}
  github_client_secret: {{ required "A .Values.creds.github.client_secret is required" .Values.creds.github.client_secret | b64enc }}
  slack_client_id: {{ required "A .Values.creds.slack.client_id is required" .Values.creds.slack.client_id | b64enc }}
  slack_client_secret: {{ required "A .Values.creds.slack.client_secret is required" .Values.creds.slack.client_secret | b64enc }}
