apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-creds"
  labels:
    app: creds
spec:
  selector:
    app: creds
  ports:
    - name: http-internal
      port: 9000
      targetPort: http-internal
    - name: http-external
      port: 9001
      targetPort: http-external
