apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-gcp-secretmanager-key"
type: Opaque
data:
  key.json: {{ required "A .Values.creds.gcp_secretmanager_key is required" .Values.creds.gcp_secretmanager_key | b64enc }}
